#ifndef _DISPLAY_AUTO_GEN_
#define _DISPLAY_AUTO_GEN_
/**************************************************
 ** Lucas-Nuelle Display Control Variable File.
 * 
 * Autogenerated Variable File from Display Control
 * Input and Output Blocks.
 * 
 * Model: Batman_Code
 * Date:  03-Jun-2015 16:17:43
 **************************************************/


#include "DSP2833x_Device.h"
#include "DSP2833x_GlobalPrototypes.h"
#include "rtwtypes.h"




/*-- Index --*/
volatile int16_T LNPC_VarIndex = 0;


/*-- Global Variables --*/

/*-- Variable Names --*/
volatile char *LNPC_Names[] = {
     "dummy",
};

/*-- Unit Names --*/
volatile char *LNPC_UnitNames[] = {
     "dummy",
};

/*-- Variable Address --*/
volatile int16_T *LNPC_Address[] = {
     0,
};

/*-- Variable Upper Saturation Limit --*/
volatile int16_T LNPC_UpperSaturation[] = {
     0,
};

/*-- Variable Lower Saturation Limit --*/
volatile int16_T LNPC_LowerSaturation[] = {
     0,
};

/*-- Modifiable Variable Type --*/
volatile char LNPC_Modifiable[] = {
     0,
};





/*-- Error Index --*/
volatile uint16_T LNEC_Index = 1;


/*-- Variable Names --*/
volatile char *LNEC_ErrorStrings[] = {
     "dummy",
};



#endif //_DISPLAY_AUTO_GEN_

